// BR-01: The official Ticket Number is generated by the backend and must be
// unique. Format: TKT-<year>-<id zero-padded to 6 digits>.
export function formatTicketNumber(id: number, year: number = new Date().getFullYear()): string {
    return `TKT-${year}-${String(id).padStart(6, "0")}`;
  }